#
# Run repoman via travis
# Based on https://github.com/mrueg/repoman-travis
#
language: python
python:
    - pypy3
before_install:
    - pip install lxml pyyaml
before_script:
    - mkdir travis-overlay
    - shopt -s extglob
    - mv !(travis-overlay) travis-overlay/
    - mv .git .travis_repoman-copyright.patch travis-overlay/
    - wget "https://gitweb.gentoo.org/proj/portage.git/snapshot/portage-2.3.78.tar.gz" -O portage.tar.gz
    - wget "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" -O portage-tree.tar.gz
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /var /var/cache
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p /etc/portage /var/cache/distfiles /var/db/repos/gentoo
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
    - tar xzf portage.tar.gz -C /tmp
    - tar xzf portage-tree.tar.gz -C /var/db/repos/gentoo --strip-components=1
    - cp /tmp/portage*/cnf/repos.conf /etc/portage/
    - ln -s /tmp/travis-overlay/profiles/linux/amd64/workstation/ /etc/portage/make.profile
    - mv travis-overlay /tmp
    - cd /tmp/portage*/repoman
    - patch -p1 < /tmp/travis-overlay/.travis_repoman-copyright.patch
    - cd /tmp/travis-overlay
script:
    - if [ `command -v travis_wait` ]; then tw="travis_wait 30"; fi
    - ${tw} python ../portage*/repoman/bin/repoman full -d
